app/views/base.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# filename: app/views/base.py


from flask import Blueprint, redirect, url_for

base = Blueprint('base', __name__)


@base.route('/', methods=["GET"])
def root():
    return "Hello World !"

@base.route('/favicon.ico', methods=["GET"])
def favicon():
    return redirect(url_for('static', filename="assets/favicon.ico"))

@base.route('/robots.txt')
def robots():
    return redirect(url_for('static', filename="robots.txt"))

app/views/order.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# filename: app/views/order.py


import time
import datetime
from functools import wraps
from flask import Blueprint, render_template, url_for, redirect, request,\
    make_response, jsonify, abort

from ..libs.compat import json, JSONDecodeError
from ..libs.log import Logger
from ..libs.config import GeneralConfig
from ..libs.db import OrderDB
from ..libs.email import OrderMailer
from ..libs.safety import OrderSign, RegisterToken, SerialNumSign,\
    OrderCookiesAESCipher, OrderRedirectAESCipher
from ..libs.utils import error_json
from ..libs.errors import FormKeysError, FormNullValueError, FormIllegalValueError,\
        QueryMissingError,\
    OrderChksnVerifyError, InvalidOrderInfoError, RegisterTokenVerifyError,\
        SerialNumSignVerifyError,\
    OrderRepeatError, OrderNotFoundError


order = Blueprint('order', __name__)

logger = Logger('views.order')
generalCfg = GeneralConfig()
orderSign = OrderSign()
registerToken = RegisterToken()
serialNumSign = SerialNumSign()
orderCookiesAESCipher = OrderCookiesAESCipher()
orderRedirectAESCipher = OrderRedirectAESCipher()
orderMailer = OrderMailer()

TypeMap = {
        "dust": "清灰",
        "hardware": "硬件",
        "software": "软件",
        "other": "其他",
    }


def _get_appointment_options(start, end, span):
    """ 生成预约时段选项 """
    pClock = lambda clockStr: datetime.datetime.strptime(clockStr, "%H:%M")
    fClock = lambda clockObj: datetime.datetime.strftime(clockObj, "%H:%M")

    start, end = map(pClock, (start, end))
    span = datetime.timedelta(minutes=span)

    options = []
    now = start
    while True:
        if now + span < end:
            options.append("{}-{}".format(fClock(now), fClock(now + span)))
            now += span
        else:
            options.append("{}-{}".format(fClock(now), fClock(end)))
            break

    return options


Active = generalCfg.getboolean('route', 'active')
Allow_Register = generalCfg.getboolean('route', 'allow_register')

Date = generalCfg.get('activity', 'date')
Site = generalCfg.get('activity', 'site')
Start = generalCfg.get('activity', 'start')
End = generalCfg.get('activity', 'end')
Span = generalCfg.getint('activity', 'span')
Next = generalCfg.get('activity', 'next')

Options = _get_appointment_options(Start, End, Span)


def verify_register_token(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            token = request.args.get("token") or request.form.get("token") or None
            if token is None or registerToken.verify(Date, token) == False:
                raise RegisterTokenVerifyError
        except Exception as err:
            # logger.exception(err)
            return jsonify(error_json(err))
        else:
            return func(*args, **kwargs)
    return wrapper


@order.route('/', methods=["GET"])
def root():
    return redirect(url_for("order.page_home"))


@order.route('/page', methods=["GET"])
def page():
    return redirect(url_for("order.page_home"))


@order.route('/api', methods=["GET","POST"])
def api():
    return abort(403)


@order.route('/page/inactive', methods=["GET"])
def page_inactive():
    if Active:
        if request.args.get("no_register") == "True":
            return render_template("order/inactive.html", no_register=True, date=Date, start=Start, end=End)
        else:
            abort(404) # 正常活动期间不能访问
    else:
        return render_template("order/inactive.html", next=Next)


@order.route('/page/home', methods=["GET"])
def page_home():
    if Active:
        # return render_template("order/home.html")
        return redirect(url_for('order.page_guide'))
    else:
        return redirect(url_for('order.page_inactive'))


@order.route("/page/guide", methods=["GET"])
def page_guide():
    if Active:
        return render_template("order/guide.html")
    else:
        return redirect(url_for('order.page_inactive'))


@order.route('/page/new', methods=["GET"])
def page_new():
    if Active:
        orderDB = OrderDB()

        appointments = dict.fromkeys(Options, 0)
        for name, count in orderDB.origin_cur.execute("""
                    SELECT appointment, count(appointment) FROM orders
                    WHERE day == ? AND status == 0
                    GROUP BY appointment
                """, (Date,)).fetchall():
            appointments[name] = count
        appointments = [dict(zip(["appointment", "sum"], item)) for item in sorted(appointments.items())]

        if orderDB:
            orderDB.close()

        return render_template("order/new.html", date=Date, site=Site, start=Start, end=End,\
                                     options=Options, appointments=appointments)
    else:
        return redirect(url_for('order.page_inactive'))


@order.route('/page/check', methods=["GET"])
def page_check():
    if Active:
        try:
            orderDB = OrderDB()
            orderCache = request.cookies.get("order")
            orderInfo = {}
            if orderCache is not None:
                try:
                    cookie = orderCookiesAESCipher.decrypt(orderCache)
                    orderInfo = orderDB.execute("""
                                SELECT * FROM orders
                                WHERE orderID == ? and status == 0
                            """, (cookie["orderID"],)).fetchone()
                except Exception as err:
                    # logger.exception(err)
                    #raise err
                    pass
        except Exception as err:
            # logger.exception(err)
            resp = jsonify(error_json(err))
        else:
            resp = make_response(render_template("order/check.html", order=orderInfo))
        finally:
            if orderDB:
                orderDB.close()
            return resp
    else:
        return redirect(url_for('order.page_inactive'))


@order.route("/page/register", methods=["GET"])
@verify_register_token
def page_register():
    if not Active:
        return redirect(url_for('order.page_inactive'))
    elif not Allow_Register:
        return redirect(url_for('order.page_inactive', no_register=True))
    else:
        return render_template("order/register.html")


@order.route("/page/result", methods=["GET"])
@verify_register_token
def page_result():
    if not Active:
        return redirect(url_for('order.page_inactive'))
    elif not Allow_Register:
        return redirect(url_for('order.page_inactive', no_register=True))
    else:
        try:
            try:
                queueID, sign = map(request.args.__getitem__, ("serial_num","sign"))
                queueID = int(queueID)
            except KeyError:
                raise QueryMissingError

            if serialNumSign.verify({"queueID": queueID, "date": Date}, sign) == False:
                raise SerialNumSignVerifyError

            orderDB = OrderDB()

            orderID = orderDB.single_cur.execute("""
                        SELECT orderID FROM queue
                        WHERE queueID == ?
                    """, (queueID,)).fetchone()

            orderInfo = orderDB.execute("""
                        SELECT * FROM orders
                        WHERE orderID == ?
                    """, (orderID,)).fetchone()

            interval = orderDB.single_cur.execute("""
                        SELECT count(*)
                        FROM queue AS q
                        INNER JOIN orders AS o ON q.orderID == o.orderID
                        WHERE q.status IN (0,1)
                        AND o.day == ?
                        AND q.queueID != ? -- 去掉自己
                    """, (Date, queueID)).fetchone()

            if orderDB:
                orderDB.close()

            return render_template("order/result.html", queueID=queueID, interval=interval, order=orderInfo)

        except Exception as err:
            return jsonify(error_json(err))


@order.route("/page/order", methods=["GET"])
def page_order():
    if Active:
        try:
            try:
                action, orderInfo = map(request.args.__getitem__, ("action","order"))
            except KeyError:
                raise QueryMissingError
            try:
                orderInfo = orderRedirectAESCipher.decrypt(orderInfo)
            except Exception as err:
                # logger.exception(err)
                raise InvalidOrderInfoError
        except Exception as err:
            return jsonify(error_json(err))
        else:
            return render_template("order/order.html", action=action, order=orderInfo)
    else:
        return redirect(url_for('order.page_inactive'))


@order.route('/api/create', methods=["POST"])
def api_create():
    try:
        orderInfo = dict(request.form.items())

        if orderInfo.keys() != {"email","wechat","model","type","description","appointment"}:
            raise FormKeysError

        for k, v in orderInfo.items():
            orderInfo[k] = v = v.strip() # strip
            if k in ("email","type","appointment") and v == "": # 必填项为空
                raise FormNullValueError
            if k == "type":
                if v not in TypeMap:
                    raise FormIllegalValueError
                else:
                    orderInfo[k] = TypeMap[v]
            if k == "appointment" and v not in Options:
                raise FormIllegalValueError

        orderDB = OrderDB()

        if orderDB.execute("""
                    SELECT * FROM orders
                    WHERE email == ? AND day == ? AND status == 0
                """, (orderInfo["email"], Date)).fetchone():
            raise OrderRepeatError # 单个邮箱单次活动只能创建一个订单

        orderInfo.update(day=Date, site=Site, status=0, create_time=int(time.time()))
        cur = orderDB.insert_one("orders", orderInfo)
        orderID = cur.lastrowid

        orderInfo.update(orderID=orderID)
        orderInfo.update(chksn=orderSign.create(orderInfo))

        orderMailer.send(orderInfo)

app/templates/order/base.html
{#
    filename: base.html
    description: order 模板

    blocks:
      title
      body
      script
#}

{% import "site-base.html" as base %}

{% set title -%}
  {% block title %}{% endblock title %} - EECS Volunteer
{%- endset %}

{% set nav %}
  <ul class="nav nav-tabs navbar-expand">
    <li class="nav-item">
      <a href="{{ url_for('order.page_guide') }}" class="nav-link">说明</a>
    </li>
    <li class="nav-item">
      <a href="{{ url_for('order.page_new') }}" class="nav-link">预约</a>
    </li>
    <li class="nav-item">
      <a href="{{ url_for('order.page_check') }}" class="nav-link">查询＆撤销</a>
    </li>
  </ul>
{% endset %}

<!DOCTYPE html>
<html>
  {{ base.head(title) }}
<body>
  <div class="container">
    {{ base.header("预约平台", nav) }}
    {% block body %}{% endblock body %}
    {{ base.footer }}
    {{ base.script }}
    {#{% block script %}{% endblock script %}#}
  </div>
</body>
</html>

app/templates/order/check.html
{#
    filename: check.html
    description: 查询页
#}

{% extends "order/base.html" %}
{% block title %}Check Order{% endblock title %}

{% block body %}
<div class="row mb-3">
  <div class="col-12">
    <h4>查询预约</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <form id="form-check" action="{{ url_for('order.api_check') }}" method="POST">
      <div class="form-group row">
        <label for="form-email" class="col-form-label col-sm-3 col-md-2">邮箱：</label>
        <div class="col">
          <input type="email" id="form-email" name="email" class="form-control" placeholder="Email" required="required">
          <div class="invalid-feedback" hidden="hidden">该邮箱下未找到有效订单</div>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary btn-block mt-4">查询订单</button>
    </form>
  </div>
</div>
{% if order %}
<div class="row mt-5 mb-3">
  <div class="col-12">
    <h4>历史预约</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <p>预约单号： <span class="font-weight-bold">{{ order.orderID }}</span></p>
    <p>创建时间： <span>{{ order.create_time|strftime }}</span></p>
    <p>订单状态： {% if order.status == 0 %}
                  <span class="text-success font-weight-bold">成功预约</span>
                {% elif order.status == 1 %}
                  <span class="text-warning font-weight-bold">已撤销</span>
                {% else %}
                  <span class="text-danger font-weight-bold">异常订单</span>
                {% endif %}</p>
    <p>邮箱： 　　<span>{{ order.email }}</span></p>
    <p>维修类型： <span>{{ order.type }}</span></p>
    <p>电脑型号： <span>{{ order.model }}</span></p>
    <p>问题描述： <span>{{ order.description }}</span></p>
    <p>活动安排： <span class="font-weight-bold">{{ order.day }}　{{ order.site }}</span></p>
    <p>预约时段： <span class="font-weight-bold">{{ order.appointment }}</span></p>
  </div>
</div>
{% endif %}
{% endblock body%}

{% block script %}
<script type="text/javascript">
  "use strict";

  $("form#form-check").submit(function() {
    var form = $(this);
    $.ajax({
      url: form.attr("action"),
      type: form.attr("method"),
      data: form.serialize(),
    })
    .done(function(res) {
      switch (res.errcode) {
        case 0:
          window.location.href = res.redirect;
          break;
        case 302: // 订单未找到
          var emailInput = form.find('input#form-email');
          emailInput.addClass("is-invalid").next("div.invalid-feedback").removeAttr('hidden');
          emailInput[0].oninput = function() {
            $(this).removeClass("is-invalid").next("div.invalid-feedback").attr('hidden', 'hidden');
          };
          break;
        default:
          console.error(res);
          throw new Error(res.errmsg);
          break;
      }
    })
    .fail(function(res) {
      throw new Error(res);
    });
    return false;
  });
</script>
{% endblock script %}

app/templates/order/guide.html
{#
    filename: guide.html
    description: 使用说明
#}

{% extends "order/base.html" %}
{% block title %}Guide{% endblock title %}

{% block body %}
<div class="row mb-3">
  <div class="col-12">
    <h4 class="mb-3">网站简介</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <p>欢迎使用信科青协电脑小队的预约系统！</p>
    <p>该系统为修机志愿活动提供线上预约服务，其主要作用是分散的机主的到场时间，避免出现人员拥挤，排队等待时间太长的问题。</p>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <h4>预约挂号流程</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <p>1、首先，您需要在 <b>“预约”页</b> 下建立一个订单，预约成功后，我们将会把订单信息发送至您所填的 <b>邮箱</b><span class="text-muted"><small>（请务必确保所填邮箱可用！每次活动，每个邮箱下只能存在一个有效订单！）</small></span>。<b>活动开始前，请务必保留好这封邮件！</b></p>
    <p>2、遵循所填的 <b>预约时段</b> 到场维修。</p>
    <p>3、活动时，您还需要现场挂号排队。到场后，扫描我们提供的二维码，填写您的 <b>邮箱</b> 确认订单，并领取一个流水号。</p>
    <p>4、记住您的流水号，并耐心等待志愿者叫号。</p>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <h4>注意事项</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <p>1、如果您没有提前预约而直接到场修机，也需要依据上述流程，<b>先预约，后挂号排队</b>。</p>
    <p>2、您可以在 <b>“查询/撤销”页</b> 通过 <b>预约邮箱</b> 查询和撤销订单。</p>
    <p>3、对于 <b>撤销</b> 操作，您需要填写我们提供的 <b>校验码</b> 来确保操作的真实性。校验码会在您预约的时候连同订单信息一同发送至您的邮箱，您可以登录预约邮箱获得校验码。校验码还会在您预约成功时连同订单信息 <b>唯一地</b> 显示一次，<b>强烈建议您 截屏 保存订单信息</b>。</p>
    <p>4、撤销成功后，您还可以重新使用之前所填的邮箱创建新的订单。</p>
  </div>
</div>
{% endblock body%}

app/templates/order/home.html
{#
    filename: home.html
    description: 首页
#}

{% extends "order/base.html" %}
{% block title %}Home{% endblock title %}

{% block body %}
<div class="row">
  <div class="col-12">
    <h4 class="mb-3">关于电脑小队</h4>
    <p>以下省略xxx字</p>
  </div>
</div>
{% endblock body%}

app/templates/order/inactive.html
{#
    filename: inactive.html
    description: 非活动跳转页
#}

{% extends "order/base.html" %}
{% block title %}Inactive{% endblock title %}

{% block body %}
<div class="row">
  <div class="col-12">
    {% if no_register %}
    <h4 class="mb-3">活动尚未进行</h4>
    <p>本次活动时间： {{ date }}　{{ start }} ~ {{ end }}</p>
    {% else %}
    <h4 class="mb-3">最近不出摊，敬请期待下期活动～</h4>
    <p>下期活动时间： <span class="font-weight-bold">{{ next }}</span></p>
    {% endif %}
  </div>
</div>
{% endblock body %}

app/templates/order/new.html
{#
    filename: new.html
    description: 新建预约
#}

{% extends "order/base.html" %}
{% block title %}New Order{% endblock title %}

{% block body %}
<div class="row mb-3">
  <div class="col-12">
    <h4>活动安排</h4>
  </div>
</div>
<div class="row mb-4">
  <div class="col-12">
    <p>时间： <span class="font-weight-bold">{{ date }}　{{ start }} ~ {{ end }}</span></p>
    <p>地点： <span class="font-weight-bold">{{ site }}</span></p>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <h4>当前预约</h4>
  </div>
</div>
<div class="row mb-4">
  <div class="col-12">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th scope="col">可选时段</th>
          <th scope="col">当前预约</th>
          <th scope="col">状态</th>
        </tr>
      </thead>
      <tbody>
      {% for item in appointments %}
        {% set sum = item.sum %}
        <tr>
          <th scope="row">{{ item.appointment }}</th>
          <td>{{ sum }}</td>
        {% if sum < 10 %}
          <td class="font-weight-bold text-success">空闲</td>
        {% elif sum < 20 %}
          <td class="font-weight-bold text-warning">忙碌</td>
        {% else %}
          <td class="font-weight-bold text-danger">爆满</td>
        {% endif %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <h4>新建预约</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <form id="form-order" action="{{ url_for('order.api_create') }}" method="POST">
      <div class="form-group row">
        <label for="form-email" class="col-form-label col-sm-3 col-md-2">邮箱：</label>
        <div class="col">
          <input type="email" id="form-email" name="email" class="form-control" placeholder="Email" required="required">
          <div class="invalid-feedback" hidden="hidden">该邮箱下已存在有效预约订单</div>
        </div>
      </div>
      <div class="form-group row">
        <label for="form-wechat" class="col-form-label col-sm-3 col-md-2">微信号：</label>
        <div class="col">
          <input type="text" id="form-wechat" name="wechat" class="form-control" placeholder="Wechat ID">
        </div>
      </div>
      <div class="form-group row">
        <label for="form-computer-model" class="col-form-label col-sm-3 col-md-2">电脑型号：</label>
        <div class="col">
          <input type="text" id="form-computer-model" name="model" class="form-control" placeholder="Computer Model">
        </div>
      </div>
      <div class="form-group row align-items-center">
        <label class="col-form-label col-sm-3 col-md-2">维修类型：</label>
        <div class="col">
          <div class="form-check form-check-inline">
            <input type="radio" id="form-problem-type-dust" name="type" class="form-check-input" value="dust" checked="checked">
            <label for="form-problem-type-dust" class="form-check-label">清灰</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="radio" id="form-problem-type-hardware" name="type" class="form-check-input" value="hardware">
            <label for="form-problem-type-hardware" class="form-check-label">硬件</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="radio" id="form-problem-type-software" name="type" class="form-check-input" value="software">
            <label for="form-problem-type-software" class="form-check-label">软件</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="radio" id="form-problem-type-other" name="type" class="form-check-input" value="other">
            <label for="form-problem-type-other" class="form-check-label">其他</label>
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="form-problem-description" class="col-form-label col-sm-3 col-md-2">问题描述：</label>
        <div class="col">
          <textarea class="form-control" id="form-problem-description" name="description" class="form-control" placeholder="Problem Description" rows="3"></textarea>
        </div>
      </div>
      <div class="form-group row">
        <label for="form-appointment" class="col-form-label col-sm-3 col-md-2">预约时段：</label>
        <div class="input-group col">
          <select id="form-appointment" name="appointment" form="form-order" class="form-control">
          {% for opt in options %}
            <option value="{{ opt }}" {% if loop.index == 1 %}selected="selected"{% endif %}>{{ opt }}</option>
          {% endfor %}
          </select>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary btn-block mt-4">提交订单</button>
    </form>
  </div>
</div>
{% endblock body%}

{% block script %}
<script type="text/javascript">
  "use strict";

  $("form#form-order").submit(function() {
    var form = $(this);
    $.ajax({
      url: form.attr('action'),
      type: form.attr('method'),
      data: form.serialize(),
    })
    .done(function(res) {
      switch (res.errcode) {
        case 0:
          window.location.href = res.redirect;
          break;
        case 301: // 表单重复创建
          var emailInput = form.find('input#form-email');
          emailInput.addClass("is-invalid").next("div.invalid-feedback").removeAttr('hidden');
          emailInput[0].oninput = function() {
            $(this).removeClass("is-invalid").next("div.invalid-feedback").attr('hidden', 'hidden');
          };
          break;
        default:
          console.error(res);
          throw new Error(res.errmsg);
          break;
      };
    })
    .fail(function(res) {
      throw new Error(res);
    });
    return false;
  });
</script>
{% endblock script %}

app/templates/order/order.html
{#
    filename: order.html
    description: 订单信息
#}

{% extends "order/base.html" %}
{% block title %}Order Infomation{% endblock title %}

{% block body %}
<div class="row mb-3">
  <div class="col-12">
    <h4>{% if action == "create" %}
          预约成功<span class="font-weight-normal text-secondary"><small><small> （订单信息已发送至您的邮箱）</small></small></span>
        {% elif action == "check" %}
          查询结果
        {% elif action == "withdraw" %}
          撤销成功
        {% elif action == "register" %}
          当前预约
        {% endif %}</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <p>预约单号： <span class="font-weight-bold">{{ order.orderID }}</span></p>
    <p>创建时间： <span>{{ order.create_time|strftime }}</span></p>
    <p>订单状态： {% if order.status == 0 %}
                  <span class="text-success font-weight-bold">成功预约</span>
                {% elif order.status == 1 %}
                  <span class="text-warning font-weight-bold">已撤销</span>
                {% else %}
                  <span class="text-danger font-weight-bold">异常订单</span>
                {% endif %}</p>
    {% if order.chksn %}
    <p>校验码： 　<span>{{ order.chksn }}</span></p>
    {% endif %}
    <p>邮箱： 　　<span>{{ order.email }}</span></p>
    <p>维修类型： <span>{{ order.type }}</span></p>
    <p>电脑型号： <span>{{ order.model }}</span></p>
    <p>问题描述： <span>{{ order.description }}</span></p>
    <p>活动安排： <span class="font-weight-bold">{{ order.day }}　{{ order.site }}</span></p>
    <p>预约时段： <span class="font-weight-bold">{{ order.appointment }}</span></p>
  </div>
</div>
{% if action == "register" %}
<div class="row mb-3">
  <div class="col-12">
    <button id="btn-register" class="btn btn-outline-primary btn-block" type="button" action="{{ url_for('order.api_register') }}" method="POST">确认挂号</button>
  </div>
</div>
{% elif order.status == 0 %}
<div class="row mb-3">
  <div class="col-12">
    <h4>撤销订单</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <form id="form-withdraw" action="{{ url_for('order.api_withdraw') }}" method="POST">
      <div class="form-group row">
        <label for="form-email" class="col-form-label col-sm-3 col-md-2">邮箱： </label>
        <div class="col">
          <input type="email" id="form-email" name="email" class="form-control" placeholder="Email" required="required" value="{{ order.email }}">
          <div class="invalid-feedback" hidden="hidden">该邮箱下未找到有效订单</div>
        </div>
      </div>
      <div class="form-group row">
        <label for="form-chksn" class="col-form-label col-sm-3 col-md-2">校验码： </label>
        <div class="col">
          <input type="text" id="form-chksn" name="chksn" class="form-control" placeholder="Authentication Code" required="required">
          <small class="form-text text-muted">从已发送的订单邮件中获得校验码</small>
          <div class="invalid-feedback" hidden="hidden">校验码错误</div>
        </div>
      </div>
      <button type="submit" class="btn btn-outline-primary btn-block mt-4">撤销订单</button>
    </form>
  </div>
</div>
{% endif %}
{% endblock body %}

{% block script %}
<script type="text/javascript">
  "use strict";

  $("button#btn-register").click(function() {
    var btn = $(this);
    var urlParams = new URLSearchParams(window.location.search);
    $.ajax({
      url: btn.attr("action") + "?token=" + urlParams.get('token'),
      type: btn.atrr("method"),
      data: {
        order: urlParams.get('order'),
      },
    })
    .done(function(res) {
      switch (res.errcode) {
        case 0:
          window.location.href = res.redirect;
          break;
        default:
          console.error(res);
          throw new Error(res.errmsg);
          break;
      }
    })
    .fail(function(res) {
      throw new Error(res);
    });
    return false;
  });

  $("form#form-withdraw").submit(function() {
    var form = $(this);
    $.ajax({
      url: form.attr('action'),
      type: form.attr('method'),
      data: form.serialize(),
    })
    .done(function(res) {
      console.log(res);
      switch (res.errcode) {
        case 0:
          console.log('ok');
          window.location.href = res.redirect;
          break;
        case 302: // 订单未找到
          var emailInput = form.find('input#form-email');
          emailInput.addClass("is-invalid").next("div.invalid-feedback").removeAttr('hidden');
          emailInput[0].oninput = function() {
            $(this).removeClass("is-invalid").next("div.invalid-feedback").attr('hidden', 'hidden');
          };
          break;
        case 201: // 校验码错误
          var chksnInput = form.find('input#form-chksn');
          chksnInput.addClass("is-invalid").next("small.form-text").attr('hidden', 'hidden').next("div.invalid-feedback").removeAttr('hidden');
          chksnInput[0].oninput = function() {
            $(this).removeClass("is-invalid").next("small.form-text").removeAttr('hidden').next("div.invalid-feedback").attr('hidden', 'hidden');
          };
          break;
        default:
          console.error(res);
          throw new Error(res.errmsg);
          break;
      }
    })
    .fail(function(res) {
      throw new Error(res);
    });
    return false;
  });
</script>
{% endblock script %}

app/templates/order/result.html
{#
    filename: result.html
    description: 挂号结果
#}

{% extends "order/base.html" %}
{% block title %}Registration Result{% endblock title %}

{% block body %}
<div class="row mb-3">
  <div class="col-12">
    <h4>挂号结果</h4>
  </div>
</div>
<div class="row mb-3">
  <div class="col-12">
    <p>流水号： <span class="font-weight-bold"><big>{{ queueID }}</big></span></p>
    <p>当前排队人数： <span class="font-weight-bold">{{ interval }} 人</span></p>
    <p>维修类型： <span>{{ order.type }}</span></p>
    <p>电脑型号： <span>{{ order.model }}</span></p>
    <p>问题描述： <span>{{ order.description }}</span></p>
  </div>
</div>
{% endblock body %}